// A large pool of tweets with placeholders for dynamic content
export const tweetPool = [
  // Pre-season tweets (Before Bahrain)
  {
    id: "preseason-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The anticipation is building! Just days until the new F1 season kicks off in Bahrain. Testing showed some interesting trends - {topTeam} looks strong, but {secondTeam} might have something special up their sleeve.`,
  },
  {
    id: "preseason-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `LIGHTS OUT AND AWAY WE GO! Well, almost! Just a few more sleeps until the 2024 F1 season begins in Bahrain. The winter testing has thrown up some surprises - who's your money on for the first race?`,
  },
  {
    id: "preseason-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: The pre-season testing data shows some fascinating trends. {topTeam} has the raw pace, but reliability could be their Achilles heel. {lowestTeam} has made significant progress over the winter.`,
  },
  {
    id: "preseason-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the long-run data from testing, {topDriver} seems to have the best race pace. But it's not all about the blue chips: {lowestDriver} has shown impressive consistency in the {lowestTeam} car. Bahrain will tell us more.`,
  },
  {
    id: "preseason-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The paddock is buzzing with anticipation ahead of Bahrain. {topTeam} looks formidable, but other teams has been sandbagging in testing. This could be one of the closest seasons in years!`,
  },
  // New pre-season tweets about midfield teams
  {
    id: "preseason-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The midfield battle looks incredibly tight this year. {thirdTeam} could be the dark horse - their car concept is quite innovative and they've made some smart technical hires over the winter.`,
  },
  {
    id: "preseason-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: The fight for third in the constructors' could be fascinating this year. {thirdTeam} has shown impressive pace in testing, but {fourthTeam} and {fifthTeam} aren't far behind. This midfield battle will be one to watch!`,
  },
  {
    id: "preseason-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the midfield teams' testing data, {thirdTeam} appears to have made the biggest step forward. Their car looks particularly strong in the medium-speed corners. Could they challenge the top two this season?`,
  },
  {
    id: "preseason-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The technical team at {fourthTeam} has been completely restructured over the winter. Early signs from testing suggest it's paying dividends - they could be regular podium contenders this year.`,
  },
  {
    id: "preseason-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `Don't sleep on {fifthTeam} this season! They've been quietly confident during testing, and their new technical director has brought some interesting concepts from their previous team. The midfield is going to be ultra-competitive!`,
  },

  // Mid-season break tweets
  {
    id: "midseason-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `As we head into the summer break, {topDriver} leads the championship. But with half the season to go, anything can happen!`,
  },
  {
    id: "midseason-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `Mid-season report: {topTeam} leads the constructors, but {secondTeam} has been closing the gap. The development race during the break will be crucial!`,
  },
  {
    id: "midseason-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: The summer break is when teams make their biggest upgrades. {lowestTeam} has a major package coming after the break - they're targeting a significant step forward.`,
  },
  {
    id: "midseason-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Mid-season analysis: {lowestDriver} has been the surprise package, consistently outperforming their car. Meanwhile, {topDriver} has been in a league of their own. The second half promises to be thrilling!`,
  },
  {
    id: "midseason-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The summer break is here! {topTeam} leads both championships, but {secondTeam} is closing in. The development race during the break could decide this championship.`,
  },
  // New mid-season tweets about midfield teams
  {
    id: "midseason-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The battle for third in the constructors' has been fascinating. {thirdTeam} currently holds the position, but {fourthTeam} has been fighting hard. This battle will go down to the wire.`,
  },
  {
    id: "midseason-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam} has been the most consistent midfield performer, but {fourthTeam} has had higher peaks. Their development paths are quite different - {thirdTeam} focusing on reliability while {fourthTeam} chases raw pace.`,
  },
  {
    id: "midseason-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The midfield battle has been incredibly tight. Not a huge gap between P3 and P6 in the constructors. Every point will be crucial in the second half of the season.`,
  },
  {
    id: "midseason-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{fifthTeam} has been the surprise package in the midfield. Despite their limited budget, they've consistently outperformed larger teams. Their technical team deserves enormous credit.`,
  },
  {
    id: "midseason-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The driver battle at {thirdTeam} has been fascinating. {thirdDriver} and their teammate have been pushing each other to new heights, which has helped them secure P3 in the standings at the break.`,
  },

  // Pre-Abu Dhabi tweets
  {
    id: "preabudhabi-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The season finale in Abu Dhabi is upon us! One last race to decide it all - this is what F1 is all about!`,
  },
  {
    id: "preabudhabi-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `It all comes down to this! Abu Dhabi will crown our 2024 champions. {topDriver} vs {secondDriver} for the drivers' title, {topTeam} vs {secondTeam} for the constructors'. The tension is palpable!`,
  },
  {
    id: "preabudhabi-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: The teams have saved their final upgrades for Abu Dhabi. {lowestTeam} has a special package for the finale - they're determined to end the season on a high.`,
  },
  {
    id: "preabudhabi-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The championship permutations are fascinating. There's excitiment in store for the end of the season. As we all know, Abu Dhabi has delivered drama before!`,
  },
  {
    id: "preabudhabi-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The paddock is electric ahead of the season finale. {lowestDriver} has a point to prove, while {topDriver} looks to cap off a remarkable season. Abu Dhabi, here we come!`,
  },
  // New pre-Abu Dhabi tweets about midfield teams
  {
    id: "preabudhabi-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The battle for third in the constructors' will go down to the wire in Abu Dhabi! Not an insurmountable divide going into the final race, with millions of dollars in prize money at stake.`,
  },
  {
    id: "preabudhabi-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam} and {fourthTeam} have both brought their final upgrades to Abu Dhabi. The fight for P3 in the constructors' is worth approximately $10-15 million in prize money - a significant sum for these teams.`,
  },
  {
    id: "preabudhabi-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The midfield battle has been one of the highlights of the season. {fifthTeam} could still snatch P4 if results go their way in Abu Dhabi.`,
  },
  {
    id: "preabudhabi-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{thirdDriver} has been the standout midfield performer this season. Their consistency has been crucial in {thirdTeam}'s fight for P3 in the constructors'. One final push needed in Abu Dhabi.`,
  },
  {
    id: "preabudhabi-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `Don't forget the intense battle for P6 between {sixthTeam} and {seventhTeam}! Benefits for next season are on the line. Every position in Abu Dhabi will be crucial for their final championship standing.`,
  },

  // Post-season tweets
  {
    id: "postseason-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `What a season it's been! Congratulations to {championDriver} on their {championDriverTitles} world championship. The way they've driven this year has been nothing short of spectacular.`,
  },
  {
    id: "postseason-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `And that's a wrap on the 2024 F1 season! {championTeam} takes the constructors' championship in style. Their consistency and development throughout the year has been remarkable.`,
  },
  {
    id: "postseason-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Season review: {lowestTeam} has made significant progress, while {championTeam} has set new standards. The development race never stops - teams are already working on their 2025 cars!`,
  },
  {
    id: "postseason-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking back at 2024: {lowestDriver} has been the revelation of the season, consistently outperforming their car. Meanwhile, {championDriver} has been in a league of their own.`,
  },
  {
    id: "postseason-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The 2024 season will be remembered for {championDriver}'s dominance and {lowestTeam}'s remarkable progress. The 2025 regulations are already creating excitement in the paddock!`,
  },
  // New post-season tweets about midfield teams
  {
    id: "postseason-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Congratulations to {thirdTeam} for securing P3 in the constructors' championship! They've been the best of the rest all season, and thoroughly deserve their position as the leading midfield team.`,
  },
  {
    id: "postseason-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam}'s journey to P3 in the constructors' has been fascinating. Their technical restructure two years ago is now bearing fruit. The additional prize money will further strengthen their position for 2025.`,
  },
  {
    id: "postseason-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The midfield battle was one of the highlights of 2024. {fourthTeam} will be disappointed to miss out on P3, but they've shown great progress. Their car concept has clear potential for further development.`,
  },
  {
    id: "postseason-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{fifthTeam} has been the efficiency champions of 2024. With one of the smallest budgets on the grid, they've consistently punched above their weight to secure P5 in the constructors'.`,
  },
  {
    id: "postseason-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The driver of the day in Abu Dhabi, {thirdDriver}, caps off a stellar season. Their performances have been crucial in {thirdTeam}'s successful campaign. A future champion in the making?`,
  },

  // More tweets about lower-ranked teams
  {
    id: "lowerteams-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{lowestTeam} has been quietly making progress. Their car concept is unique, and they're starting to see the benefits. Don't be surprised if they're fighting for points more regularly next season.`,
  },
  {
    id: "lowerteams-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The battle at the back is just as intense as the fight at the front! {lowestDriver} has been extracting everything from that {lowestTeam} car. Their qualifying performances have been particularly impressive.`,
  },
  {
    id: "lowerteams-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {lowestTeam} has brought some interesting upgrades to {currentRace}. Their technical team is thinking outside the box, and it's starting to pay dividends.`,
  },
  {
    id: "lowerteams-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data shows {lowestDriver} is actually faster in sector 2 than several midfield drivers. If {lowestTeam} can improve their straight-line speed, they could be regular points scorers.`,
  },
  {
    id: "lowerteams-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{lowestTeam} has a clear vision for their future in F1. Their technical structure is solid, and they're making steady progress. Don't write them off for next season!`,
  },

  // New tweets about midfield teams and battles
  {
    id: "midfield-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The midfield battle between {thirdTeam}, {fourthTeam}, and {fifthTeam} is providing some of the best racing this season. Their cars are closely matched, which means driver skill is making the difference.`,
  },
  {
    id: "midfield-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdTeam} has been the surprise package this season! Currently P3 in the constructors' and consistently challenging the top teams. Their technical department deserves enormous credit.`,
  },
  {
    id: "midfield-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {fourthTeam}'s upgrade package has delivered exactly what they promised. Their car is now much stronger in high-speed corners, which should help them at {currentRace} this weekend.`,
  },
  {
    id: "midfield-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the data, {fifthTeam} has the strongest straight-line speed in the midfield. That's helping them defend positions, but they're losing time in the technical sections compared to {thirdTeam}.`,
  },
  {
    id: "midfield-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The atmosphere at {thirdTeam} is incredibly positive right now. They're punching above their weight, and there's a real belief they can maintain P3 in the constructors' until the end of the season.`,
  },
  {
    id: "midfield-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{thirdDriver} has been the standout midfield performer this season. Consistently extracting the maximum from the {thirdTeam} car and regularly challenging the top teams. Future world champion material.`,
  },
  {
    id: "midfield-7",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The battle for P5 between {fifthTeam} and {sixthTeam} is heating up! Every race finish counts in this tight midfield contest.`,
  },
  {
    id: "midfield-8",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {sixthTeam} has brought a completely new floor design to {currentRace}. They're targeting {fifthTeam}'s P5 position, and early data from practice looks promising.`,
  },
  {
    id: "midfield-9",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{seventhTeam} has been inconsistent this season, but when they get the setup right, they can challenge for serious points. Their car seems particularly sensitive to track temperature.`,
  },
  {
    id: "midfield-10",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The technical battle in the midfield is fascinating. {thirdTeam}, {fourthTeam}, and {fifthTeam} have completely different car concepts, yet their performance is remarkably similar. F1's technical diversity at its best.`,
  },

  // Tweets specifically about the 3rd place team
  {
    id: "thirdteam-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{thirdTeam} has made remarkable progress this season. Their car development rate has been impressive, and they're now regularly the third-fastest team. Could they challenge the top two next year?`,
  },
  {
    id: "thirdteam-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdDriver} has been extracting everything from that {thirdTeam} car. Their qualifying performances have been particularly impressive - regularly making it into Q3 and occasionally troubling the top teams.`,
  },
  {
    id: "thirdteam-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam}'s technical director explained their development philosophy to me today. They're focusing on incremental gains rather than big updates, and it's clearly working.`,
  },
  {
    id: "thirdteam-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data shows {thirdTeam} is particularly strong in medium-speed corners. That's helping them at tracks like {currentRace}, where they could be in the mix for a podium if the top teams slip up.`,
  },
  {
    id: "thirdteam-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The atmosphere at {thirdTeam} is electric right now. They've consolidated their position as the third-best team, and there's a real belief they can close the gap to {secondTeam} before the end of the season.`,
  },
  {
    id: "thirdteam-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{thirdTeam}'s pit crew has been exceptional this season. Consistently executing sub-2.5 second stops, which has helped them gain crucial positions in the tight midfield battle.`,
  },
  {
    id: "thirdteam-7",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdTeam} now has {sortedTeams[2].points} points in the constructors' championship. That's already more than their entire haul from last season, with {totalRaces - currentRaceIndex} races still to go!`,
  },
  {
    id: "thirdteam-8",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam}'s factory has been working 24/7 to bring updates to every race. Their commitment to development is paying off with their strong P3 position in the championship.`,
  },
  {
    id: "thirdteam-9",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{thirdTeam}'s race strategists have been making all the right calls this season. Their decision-making under pressure has been excellent, particularly in the mixed-condition races.`,
  },
  {
    id: "thirdteam-10",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The partnership between {thirdDriver} and his race engineer has been one of the success stories of the season. They've elevated each other to new heights, and the results speak for themselves.`,
  },

  // Martin Brundle tweets
  {
    id: "brundle-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Incredible performance from {topDriver} this season! The way they're driving that {topDriverTeam} car is simply masterclass. {topDriverPoints} points already and we're only at race {currentRaceIndex}.`,
  },
  {
    id: "brundle-2",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The battle between {topDriver} and {secondDriver} reminds me of the Senna-Prost era. Pure racing at its finest. This is what F1 is all about!`,
  },
  {
    id: "brundle-3",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Just walked the track at {currentRace}. Turn 4 looks particularly tricky this year with the new surface. Expect some drivers to struggle there during the race.`,
  },
  {
    id: "brundle-4",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{americarTeam} has made progress for a team in just their second season. Currently P{americarPosition} in the constructors' standings - they're working hard to move up the grid.`,
  },
  {
    id: "brundle-5",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The gap between {topTeam} and {secondTeam} is closing. We could see a real fight for the constructors' title if this trend continues.`,
  },
  {
    id: "brundle-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{lastRaceWinner}'s drive at the last race was exceptional. Controlled the pace perfectly and never looked troubled. Championship-caliber performance.`,
  },
  {
    id: "brundle-7",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The technical directive issued before {currentRace} could shake up the order. Several teams might need to modify their floor designs.`,
  },
  {
    id: "brundle-8",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{currentRace} has always been a circuit where driver skill can overcome car deficiencies. Expecting some surprises this weekend.`,
  },
  {
    id: "brundle-9",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Interesting to see {thirdDriver} consistently outperforming their teammate. They're extracting everything from that car.`,
  },
  {
    id: "brundle-10",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The championship battle is far from over. With {totalRaces - currentRaceIndex} races to go, there are still plenty of points on the table.`,
  },
  {
    id: "brundle-11",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Reliability could be the deciding factor in this championship. {topTeam} has had fewer DNFs than {secondTeam} so far.`,
  },
  {
    id: "brundle-12",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{americarDriver1} showing flashes of real talent. With more development on that car, they could be fighting for points more regularly.`,
  },
  {
    id: "brundle-13",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The new regulations have certainly achieved closer racing. The field is more compressed than we've seen in years.`,
  },
  {
    id: "brundle-14",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Tire management will be crucial at {currentRace}. The abrasive surface combined with high temperatures makes for a strategic challenge.`,
  },
  {
    id: "brundle-15",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{topDriver} seems to have found another gear in recent races. Their confidence in the car is visibly growing.`,
  },
  // New Martin Brundle tweets about midfield teams
  {
    id: "brundle-16",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The midfield battle between {thirdTeam} and {fourthTeam} is providing some of the best racing this season. Not many points between them in the fight for P3.`,
  },
  {
    id: "brundle-17",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{thirdDriver} has been exceptional in that {thirdTeam} car. They're maximizing every opportunity and regularly scoring big points. A future star in the making.`,
  },
  {
    id: "brundle-18",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{fifthTeam} has the most efficient operation in F1. With one of the smallest budgets, they're consistently outperforming teams with far greater resources. Impressive management.`,
  },

  // David Croft tweets
  {
    id: "croft-1",
    author: "David Croft",
    handle: "CroftyF1",
    content: `And it's {lastRaceWinner} who takes the win! What a drive! The championship battle is heating up as we head to {currentRace}. Can't wait for the next race weekend!`,
  },
  {
    id: "croft-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `LIGHTS OUT AND AWAY WE GO! What a start from {topDriver}! Absolutely brilliant getaway from the grid at {currentRace}!`,
  },
  {
    id: "croft-3",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The weather forecast for {currentRace} is looking unpredictable. Could we see a repeat of that crazy race in 2016? Rain always mixes things up!`,
  },
  {
    id: "croft-4",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{americarDriver1} showing impressive pace in the practice sessions. The {americarTeam} team has really found something in their setup this weekend.`,
  },
  {
    id: "croft-5",
    author: "David Croft",
    handle: "CroftyF1",
    content: `What a battle we're seeing between {topDriver} and {secondDriver} this season! I do wonder how we'll look back at this competition a decade or two from now. That's all the philisophical talk for now though -- interview with Christian Horner today :)`,
  },
  {
    id: "croft-6",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The atmosphere at {currentRace} is absolutely electric! Fans have been pouring in since early morning. Nothing quite like race day in Formula 1!`,
  },
  {
    id: "croft-7",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{topTeam} have now led the constructors' championship for {currentRaceIndex} consecutive races. Remarkable consistency from the entire team.`,
  },
  {
    id: "croft-8",
    author: "David Croft",
    handle: "CroftyF1",
    content: `Just {totalRaces - currentRaceIndex} races to go in this thrilling season! Every point will be crucial in the championship battle.`,
  },
  {
    id: "croft-9",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{lastRaceSecond} must be wondering what they need to do to beat {lastRaceWinner}. Another second place finish at the last race.`,
  },
  {
    id: "croft-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The start at {currentRace} is one of the most challenging on the calendar. That uphill run to Turn 1 has seen many first lap incidents over the years.`,
  },
  {
    id: "croft-11",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{americarTeam} currently P{americarPosition} in the constructors' standings. A solid foundation to build on in their second season.`,
  },
  {
    id: "croft-12",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The battle for third in the constructors' is incredibly tight! Just a handful of points separating several teams.`,
  },
  {
    id: "croft-13",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdDriver} has been the surprise of the season for me. Consistently delivering strong results in that {thirdDriver.teamName} car.`,
  },
  {
    id: "croft-14",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The DRS zones at {currentRace} have been adjusted this year. Should make for more overtaking opportunities into Turn 4.`,
  },
  {
    id: "croft-15",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{nextRace} is just around the corner! The teams will have a quick turnaround after this weekend's race at {currentRace}.`,
  },
  // New David Croft tweets about midfield teams
  {
    id: "croft-16",
    author: "David Croft",
    handle: "CroftyF1",
    content: `What a result for {thirdTeam}! Another strong points haul strengthens their grip on P3 in the constructors'. {fourthTeam} is going to have long discussions tonight.`,
  },
  {
    id: "croft-17",
    author: "David Croft",
    handle: "CroftyF1",
    content: `WHAT A MOVE by {thirdDriver}! Brilliant overtake around the outside of Turn 4. That {thirdTeam} car is working beautifully through the medium-speed corners.`,
  },
  {
    id: "croft-18",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The midfield battle is providing some of the best racing this season! {fourthTeam}, {fifthTeam}, and {sixthTeam} are separated by just tenths in qualifying and racing wheel-to-wheel every weekend.`,
  },

  // Ted Kravitz tweets
  {
    id: "kravitz-1",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Just wandering around the paddock and spotted some interesting upgrades on the {topTeam} cars. Their pace advantage is no accident - the development race is just as intense as the on-track action!`,
  },
  {
    id: "kravitz-2",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {secondTeam} have brought a completely redesigned floor to {currentRace}. Engineers expect to find at least 0.3 seconds per lap. Fascinating development battle!`,
  },
  {
    id: "kravitz-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Spotted {thirdDriver} having a long chat with their race engineer. Clearly not happy with the car balance in sector 2. They'll need to sort that before qualifying.`,
  },
  {
    id: "kravitz-4",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarTeam} garage is buzzing with activity. For a second-year team, their operation looks professional. They've brought some experienced personnel on board.`,
  },
  {
    id: "kravitz-5",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Interesting to see {topDriver}'s car up on stands in the garage. The team is making some last-minute setup changes before FP3.`,
  },
  {
    id: "kravitz-6",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{secondTeam} have brought a new front wing design to {currentRace}. It's a more aggressive concept than what we've seen from them before.`,
  },
  {
    id: "kravitz-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarTeam} car has a noticeably different cooling configuration for {currentRace}. The higher temperatures here require some specific adaptations.`,
  },
  {
    id: "kravitz-8",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Just spotted {lastRaceWinner} in deep discussion with their strategist. They're clearly leaving no stone unturned in their preparation.`,
  },
  {
    id: "kravitz-9",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Several teams struggling with porpoising through the high-speed sections at {currentRace}. The bumpy surface isn't helping matters.`,
  },
  {
    id: "kravitz-10",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{topTeam} have brought their largest upgrade package of the season to {currentRace}. New floor, sidepods, and rear wing. They're not resting on their laurels.`,
  },
  {
    id: "kravitz-11",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarDriver1} side of the garage has opted for a different setup direction than {americarDriver2}. They're still finding their optimal window with this car.`,
  },
  {
    id: "kravitz-12",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Tire degradation is higher than expected after the practice sessions. The teams might need to rethink their race strategies.`,
  },
  {
    id: "kravitz-13",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{thirdDriver}'s mechanics working flat out to fix an issue with the power unit cooling system. They should have it sorted before qualifying.`,
  },
  {
    id: "kravitz-14",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The new technical directive has forced several teams to modify their floor designs. {secondTeam} seems most affected by the changes.`,
  },
  {
    id: "kravitz-15",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{americarTeam} have a new technical director starting after {currentRace}. Big signing for them - previously worked at {topTeam}.`,
  },
  // New Ted Kravitz tweets about midfield teams
  {
    id: "kravitz-16",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdTeam} have brought a significant upgrade package to {currentRace}. New floor, revised sidepods, and updated brake ducts. They're serious about consolidating that P3 position.`,
  },
  {
    id: "kravitz-17",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Just spotted the {fourthTeam} technical director deep in conversation with their chief aerodynamicist. They're planning a major update for the next race to challenge {thirdTeam} for P3.`,
  },
  {
    id: "kravitz-18",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {fifthTeam} garage has a completely new front wing design they're testing today. It's a radical concept - much more aggressive than anything we've seen from them before.`,
  },

  // Karun Chandhok tweets
  {
    id: "chandhok-1",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the telemetry data, {secondDriver} is actually faster in sector 2, but {topDriver} makes up the time in the high-speed corners. Fascinating battle between these two!`,
  },
  {
    id: "chandhok-2",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Analyzing the race pace from practice, {topTeam} still has about 0.2s advantage per lap over {secondTeam}, but tire degradation could be the deciding factor on Sunday.`,
  },
  {
    id: "chandhok-3",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The midfield battle is incredibly tight this season. Just 0.3s covers P7 to P14 in qualifying simulations. Strategy and execution will be everything.`,
  },
  {
    id: "chandhok-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{americarTeam}'s progress curve is impressive. Their car concept is quite unique - they've gone their own way with the sidepod design and it seems to be working for their package.`,
  },
  {
    id: "chandhok-5",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The long-run pace from {topDriver} in FP2 was consistently 0.3s faster than anyone else. They look very comfortable with their race setup.`,
  },
  {
    id: "chandhok-6",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{secondTeam} seems to be struggling with tire warm-up in the cooler conditions. Could be a factor if qualifying takes place later in the evening.`,
  },
  {
    id: "chandhok-7",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data shows {americarDriver1} is particularly strong in the technical middle sector. Their car seems well-balanced through the slower corners.`,
  },
  {
    id: "chandhok-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{lastRaceWinner}'s race-winning pace at the last GP was built on exceptional tire management. They were 0.2s faster than anyone else in the final stint.`,
  },
  {
    id: "chandhok-9",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The speed trap figures show {topTeam} has the straight-line advantage, while {secondTeam} is quicker through the corners. Classic F1 development trade-off.`,
  },
  {
    id: "chandhok-10",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{thirdDriver} is consistently the fastest driver through Turn 7 - a corner that requires precise weight transfer and commitment. Impressive stuff.`,
  },
  {
    id: "chandhok-11",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The {americarTeam} car is showing good straight-line speed, but they're losing time in the high-downforce sections. Clear area for development.`,
  },
  {
    id: "chandhok-12",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the championship battle, {topDriver} has been more consistent, while {secondDriver} has had higher peaks but more off-days.`,
  },
  {
    id: "chandhok-13",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data from practice shows the soft tire has a performance delta of around 0.8s over the medium, but degrades significantly after 15 laps.`,
  },
  {
    id: "chandhok-14",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{topTeam} and {secondTeam} are taking different approaches to downforce levels at {currentRace}. {topTeam} has opted for more downforce, sacrificing some straight-line speed.`,
  },
  {
    id: "chandhok-15",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The telemetry shows {americarDriver1} is braking later and harder than {americarDriver2} at Turn 1. Different driving styles within the same team.`,
  },
  // New Karun Chandhok tweets about midfield teams
  {
    id: "chandhok-16",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Analyzing the telemetry data from {thirdTeam} and {fourthTeam}, they have completely different strengths. {thirdTeam} excels in medium-speed corners, while {fourthTeam} has better straight-line speed.`,
  },
  {
    id: "chandhok-17",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The long-run pace from {thirdDriver} in FP2 was impressive. They were consistently matching {secondTeam}'s times in the final sector. {thirdTeam} has made real progress with their car balance.`,
  },
  {
    id: "chandhok-18",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the midfield battle, {fifthTeam} has the most efficient aero package. They're generating competitive downforce levels despite having one of the smallest development budgets.`,
  },

  // Will Buxton tweets
  {
    id: "buxton-1",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} showing progress in their second year. {americarDriver1} looking particularly impressive lately.`,
  },
  {
    id: "buxton-2",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `There's something special brewing at {topTeam} this season. The harmony between team and drivers, the strategic calls, the development pace. Championship material.`,
  },
  {
    id: "buxton-3",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Paddock whispers suggest {thirdDriver} might be on the move next season. Several teams showing interest. The driver market is already heating up!`,
  },
  {
    id: "buxton-4",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The atmosphere at {currentRace} is electric! Fans have been queuing since dawn. This is what makes F1 the greatest sporting spectacle on the planet.`,
  },
  {
    id: "buxton-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Just had a fascinating chat with {topDriver} about their approach to {currentRace}. They're focused on the bigger picture - the championship.`,
  },
  {
    id: "buxton-6",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The relationship between {secondDriver} and their race engineer is one of the strongest on the grid. Their radio communications are always clear and precise.`,
  },
  {
    id: "buxton-7",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} has brought a significant upgrade package to {currentRace}. Their technical director seemed quietly confident when I spoke to him this morning.`,
  },
  {
    id: "buxton-8",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The paddock is buzzing with talk about {lastRaceWinner}'s performance at the last race. That level of dominance doesn't come along often.`,
  },
  {
    id: "buxton-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{thirdDriver} told me they've been working specifically on their qualifying performance. They know that's been their weakness this season.`,
  },
  {
    id: "buxton-10",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The team principals' press conference was spicy today! Clear tension between {topTeam} and {secondTeam} over the recent technical directive.`,
  },
  {
    id: "buxton-11",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarDriver1} has a special helmet design for {currentRace}. A tribute to their racing hero - nice touch.`,
  },
  {
    id: "buxton-12",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The drivers are all talking about the resurfaced section between Turns 5 and 7. Much smoother than last year, which should help with car balance.`,
  },
  {
    id: "buxton-13",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{topDriver} seems very relaxed despite the championship pressure. Their experience in these situations is showing.`,
  },
  {
    id: "buxton-14",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The {secondTeam} garage has been closed to media more than usual this weekend. Something special in the works, perhaps?`,
  },
  {
    id: "buxton-15",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} has a new sponsor on the car this weekend. Good to see them attracting more commercial partners in their second season.`,
  },
  // New Will Buxton tweets about midfield teams
  {
    id: "buxton-16",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Just had a fascinating chat with {thirdTeam}'s team principal. They're not just focused on securing P3 this year - they have a three-year plan to challenge for championships. Ambitious but refreshing.`,
  },
  {
    id: "buxton-17",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The atmosphere at {fourthTeam} is incredibly positive despite losing ground to {thirdTeam}. Their technical director assured me they have major upgrades coming for the next three races.`,
  },
  {
    id: "buxton-18",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{fifthTeam} continues to be the most efficient team on the grid. Their technical director explained how they're maximizing every dollar of their budget. A masterclass in resource management.`,
  },

  // Jenson Button tweets
  {
    id: "button-1",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Having raced against some of the greats, I can tell you that what {topDriver} is doing this season is special. The consistency, the race craft, the qualifying pace - complete package.`,
  },
  {
    id: "button-2",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{currentRace} was always one of my favorite circuits. The sequence through turns 5-7 is one of the most challenging in F1. Drivers who nail that section will find big time.`,
  },
  {
    id: "button-3",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Tire management will be crucial at {currentRace}. I'd expect a two-stop strategy to be fastest, but someone might try to make a one-stop work. That's where experience counts.`,
  },
  {
    id: "button-4",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Impressive to see how quickly {americarTeam} has integrated into F1. Building a team from scratch is incredibly difficult - I've seen many try and fail. They've done their homework.`,
  },
  {
    id: "button-5",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The way {topDriver} controlled the pace at the front in the last race reminded me of Lewis at his best. Making it look easy when it's anything but.`,
  },
  {
    id: "button-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{secondDriver} needs to focus on their qualifying performance. Starting behind {topDriver} puts them on the back foot immediately.`,
  },
  {
    id: "button-7",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarDriver1} has impressed me this season. They're extracting the maximum from that car and making very few mistakes.`,
  },
  {
    id: "button-8",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The start at {currentRace} is one of the trickiest on the calendar. The track narrows into Turn 1 and there's always the risk of contact.`,
  },
  {
    id: "button-9",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{thirdDriver} is one of the most underrated drivers on the grid. Consistently delivering results without much fanfare.`,
  },
  {
    id: "button-10",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The battle between {topTeam} and {secondTeam} reminds me of the McLaren-Ferrari days. Two great teams pushing each other to new heights.`,
  },
  {
    id: "button-11",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarTeam} has a solid foundation to build on. They've avoided the common first-year mistakes and have a clear development path.`,
  },
  {
    id: "button-12",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Wet weather is forecast for qualifying. That could shake up the grid - some drivers excel in those conditions while others struggle.`,
  },
  {
    id: "button-13",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{lastRaceWinner}'s overtake on {lastRaceSecond} in the last race was one of the best I've seen this season. Perfectly judged.`,
  },
  {
    id: "button-14",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The championship isn't over yet. I've seen bigger points gaps overturned in fewer races. {secondDriver} just needs a run of form.`,
  },
  {
    id: "button-15",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarDriver2} seems more comfortable with the car upgrades than {americarDriver1}. Different driving styles suit different car characteristics.`,
  },
  // New Jenson Button tweets about midfield teams
  {
    id: "button-16",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{thirdTeam}'s progress this season reminds me of Brawn GP in 2009. They've found a concept that works perfectly for the regulations and are maximizing every opportunity. Impressive stuff.`,
  },
  {
    id: "button-17",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{thirdDriver} is extracting everything from that {thirdTeam} car. Their qualifying performances have been particularly impressive - regularly making Q3 and occasionally troubling the top teams.`,
  },
  {
    id: "button-18",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The midfield battle between {fourthTeam} and {fifthTeam} is providing some of the best racing this season. Their cars have different strengths, which makes for fascinating on-track battles.`,
  },

  // Damon Hill tweets
  {
    id: "hill-1",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The battle between {topTeam} and {secondTeam} reminds me of some of the great team rivalries of the past. F1 at its best when the competition is this fierce!`,
  },
  {
    id: "hill-2",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{lastRaceWinner}'s drive last weekend was one of the best I've seen in years. Shades of Senna at Donington in '93. Sometimes you just have to sit back and applaud greatness.`,
  },
  {
    id: "hill-3",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The pressure in a championship fight is immense. I've been there. {topDriver} needs to stay focused on each race as it comes. One race at a time.`,
  },
  {
    id: "hill-4",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarTeam}'s approach is refreshing. They're not just here to make up the numbers. Their technical team has some innovative ideas, and they're not afraid to try something different.`,
  },
  {
    id: "hill-5",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{currentRace} has always been a circuit that rewards bravery. The high-speed sections separate the good from the great.`,
  },
  {
    id: "hill-6",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{secondDriver} needs to find consistency if they want to challenge for the title. The raw pace is there, but too many off-weekends.`,
  },
  {
    id: "hill-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarDriver1} is showing real potential. With more experience and a better car, they could be a future race winner.`,
  },
  {
    id: "hill-8",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The mental aspect of F1 is often overlooked. {topDriver} seems to have the psychological edge over {secondDriver} at the moment.`,
  },
  {
    id: "hill-9",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{thirdDriver} has been the surprise package this season. Consistently extracting the maximum from that car.`,
  },
  {
    id: "hill-10",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The technical regulations have produced closer racing this year. The field is more compressed than we've seen for a long time.`,
  },
  {
    id: "hill-11",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarTeam} has a solid technical foundation. Their car concept has clear potential for development.`,
  },
  {
    id: "hill-12",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{lastRaceThird}'s podium at the last race was well-deserved. They've been knocking on the door for a while.`,
  },
  {
    id: "hill-13",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The championship battle will come down to who handles the pressure better. {topDriver} has the experience advantage in that regard.`,
  },
  {
    id: "hill-14",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{currentRace} is one of the most physically demanding tracks on the calendar. Driver fitness will be a factor, especially in the closing laps.`,
  },
  {
    id: "hill-15",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarDriver2} has been overshadowed by their teammate, but there have been flashes of real speed. They just need to find consistency.`,
  },
  // New Damon Hill tweets about midfield teams
  {
    id: "hill-16",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{thirdTeam} has been the revelation of the midfield this season. Their technical team has done a remarkable job with limited resources. Reminds me of Jordan in the mid-90s.`,
  },
  {
    id: "hill-17",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The battle between {thirdTeam} and {fourthTeam} for P3 in the constructors' is providing some of the best storylines this season. Both teams have completely different philosophies but are ending up with similar performance.`,
  },
  {
    id: "hill-18",
    author: "Damon Hill",
handle: "HillF1",
    content: `{thirdDriver} is showing the kind of consistency that championship campaigns are built on. They're maximizing every opportunity in that {thirdTeam} car. Future world champion material.`,
  },

  // Nico Rosberg tweets
  {
    id: "rosberg-1",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The mental strength of {topDriver} is impressive. Championship pressure can break you - I know that better than most! They seem completely unfazed by it all.`,
  },
  {
    id: "rosberg-2",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{secondDriver} needs to find another gear if they want to challenge for this championship. The raw pace is there, but consistency wins titles.`,
  },
  {
    id: "rosberg-3",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The start at {currentRace} is one of the most critical on the calendar. I always focused extra on my launch practice here. First corner position is everything.`,
  },
  {
    id: "rosberg-4",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `For a new team like {americarTeam}, scoring points consistently in year two is a good achievement. Their management structure is clearly working well.`,
  },
  {
    id: "rosberg-5",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{topDriver}'s qualifying performances have been exceptional this season. They've outqualified their teammate {currentRaceIndex} times already.`,
  },
  {
    id: "rosberg-6",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{secondDriver} needs to focus on their race starts. They've lost positions off the line too many times this season.`,
  },
  {
    id: "rosberg-7",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarDriver1} has impressed me with their racecraft. Clean, fair, and decisive in wheel-to-wheel situations.`,
  },
  {
    id: "rosberg-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The way {lastRaceWinner} managed the gap in the last race was textbook. Never pushing too hard, never allowing their rivals to get close.`,
  },
  {
    id: "rosberg-9",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{thirdDriver} needs to capitalize on their strong qualifying performances. Too often they've slipped back in the race.`,
  },
  {
    id: "rosberg-10",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The championship battle is as much psychological as it is about car performance. {topDriver} seems to have the mental edge right now.`,
  },
  {
    id: "rosberg-11",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarTeam} has a clear vision for their future in F1. Their technical structure is solid and they're making steady progress.`,
  },
  {
    id: "rosberg-12",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{currentRace} requires absolute precision. One small mistake in the high-speed sections can cost you dearly.`,
  },
  {
    id: "rosberg-13",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{lastRaceSecond} must be frustrated with another P2 finish. So close yet so far - I know that feeling well!`,
  },
  {
    id: "rosberg-14",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The development race between {topTeam} and {secondTeam} is fascinating. Each upgrade is a direct response to the other team's innovations.`,
  },
  {
    id: "rosberg-15",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarDriver2} needs to find more consistency. The flashes of speed are there, but too many weekends where they're off the pace.`,
  },
  // New Nico Rosberg tweets about midfield teams
  {
    id: "rosberg-16",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{thirdTeam}'s progress this season has been remarkable. Their car development rate is impressive - they've found at least half a second since the start of the season.`,
  },
  {
    id: "rosberg-17",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The battle for P3 in the constructors' between {thirdTeam} and {fourthTeam} is worth watching. Both teams have completely different car concepts, but are ending up with similar performance.`,
  },
  {
    id: "rosberg-18",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{thirdDriver} is extracting everything from that {thirdTeam} car. Their qualifying performances have been particularly impressive - regularly making Q3 and occasionally troubling the top teams.`,

  // Mark Webber tweets
  {
    id: "webber-1",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{topDriver} is in the zone right now. When a driver finds that sweet spot with their car, it's a beautiful thing to watch. Reminds me of Vettel in 2013.`,
  },
  {
    id: "webber-2",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The physicality of {currentRace} is often underestimated. Drivers will lose 3-4kg during the race. The neck and shoulder strength required is immense.`,
  },
  {
    id: "webber-3",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `Strategy calls will make or break races this season. The performance delta between teams is so small that pit timing and tire choice are more crucial than ever.`,
  },
  {
    id: "webber-4",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarTeam} has brought a fresh energy to the paddock. Their technical approach is bold - high risk, high reward. That's what we need more of in F1.`,
  },
  {
    id: "webber-5",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{topDriver}'s ability to extract the maximum from the car in qualifying is remarkable. They're consistently finding those extra few tenths.`,
  },
  {
    id: "webber-6",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{secondDriver} needs to focus on their race pace. They're often quick over one lap but struggle to maintain that pace over a full stint.`,
  },
  {
    id: "webber-7",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarDriver1} has shown good racecraft this season. Clean but assertive in wheel-to-wheel battles.`,
  },
  {
    id: "webber-8",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The way {lastRaceWinner} controlled the race from the front last weekend was impressive. Never looked under pressure.`,
  },
  {
    id: "webber-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{thirdDriver} is extracting everything from that car. They're consistently outperforming what the package should be capable of.`,
  },
  {
    id: "webber-10",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The championship battle will come down to who makes fewer mistakes. The pressure is building with each race.`,
  },
  {
    id: "webber-11",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarTeam} has a solid foundation to build on. Their car concept has clear potential for development.`,
  },
  {
    id: "webber-12",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{currentRace} is one of the most physically demanding tracks on the calendar. The g-forces through the high-speed corners are brutal.`,
  },
  {
    id: "webber-13",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{lastRaceThird}'s podium at the last race was well-deserved. They've been knocking on the door for a while.`,
  },
  {
    id: "webber-14",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The development race between {topTeam} and {secondTeam} is fascinating. Each upgrade is a direct response to the other team's innovations.`,
  },
  {
    id: "webber-15",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarDriver2} has shown flashes of real speed. With more experience, they could be a regular points scorer.`,
  },
  // New Mark Webber tweets about midfield teams
  {
    id: "webber-16",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{thirdTeam} has been the surprise package this season. Their technical team has done a remarkable job with limited resources. The car is particularly strong in medium-speed corners.`,
  },
  {
    id: "webber-17",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The midfield battle between {fourthTeam} and {fifthTeam} is providing some of the best racing this season. Their cars have different strengths, which makes for fascinating on-track battles.`,
  },
  {
    id: "webber-18",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{thirdDriver} is showing the kind of consistency that championship campaigns are built on. They're maximizing every opportunity in that {thirdTeam} car. Future world champion material.`,
  },

  // Add these new tweets about third place and midfield drivers to the tweet pool

  // Tweets about third place driver
  {
    id: "thirddriver-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{thirdDriver} is in a fascinating position in this championship. Not quite in the title fight, but consistently delivering podiums. Their performances this season have been outstanding.`,
  },
  {
    id: "thirddriver-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdDriver} might not be in the championship battle, but they're having a stellar season. {thirdDriverPoints} points is an impressive haul, and they're making the most of every opportunity.`,
  },
  {
    id: "thirddriver-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {thirdDriver} has been the model of consistency this season. They've finished in the points in every race they've completed. That reliability is why they're P3 in the standings.`,
  },
  {
    id: "thirddriver-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The telemetry data shows {thirdDriver} is actually faster than {secondDriver} in the slow-speed corners. If they can improve their straight-line speed, they could challenge for wins more regularly.`,
  },
  {
    id: "thirddriver-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Just had a fascinating chat with {thirdDriver}. They're not giving up on P2 in the championship. It's still possible, and they're in it to win the big one.`,
  },
  {
    id: "thirddriver-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{thirdDriver}'s racecraft has been exceptional this season. Their overtaking is clean but assertive, and they rarely make mistakes under pressure. That's why they're P3 in the standings.`,
  },
  {
    id: "thirddriver-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{thirdDriver} reminds me a bit of myself in '94 and '95. Always there, always consistent, waiting to capitalize when the frontrunners slip up. That approach can win championships eventually.`,
  },
  {
    id: "thirddriver-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{thirdDriver} is in that difficult P3 position - not quite in the title fight but too far ahead of P4. It's mentally challenging to maintain motivation, but they're handling it well.`,
  },
  {
    id: "thirddriver-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{thirdDriver} has been extracting the maximum from their package all season. They've outperformed their teammate in {currentRaceIndex - 1} of the {currentRaceIndex} races so far. Impressive consistency.`,
  },
  {
    id: "thirddriver-10",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `Just interviewed {thirdDriver} - they're focused on securing P3 in the championship but haven't given up on catching {secondDriver}. Their determination is impressive.`,
  },

  // Tweets about midfield drivers (P4-P10)
  {
    id: "midfield-driver-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{fourthDriver} is having a breakthrough season. They're consistently extracting the maximum from that car and occasionally troubling the top three teams. Future champion material.`,
  },
  {
    id: "midfield-driver-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `What a drive from {fifthDriver} today! Fighting through from P12 to score solid points. They're making a strong case for a top team seat in the future.`,
  },
  {
    id: "midfield-driver-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {sixthDriver} has been quietly impressive this season. They've outqualified their more experienced teammate {currentRaceIndex - 3} times in {currentRaceIndex} races. The team is delighted with their progress.`,
  },
  {
    id: "midfield-driver-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the data, {seventhDriver} is actually one of the fastest drivers in sector 2. Their car lacks straight-line speed, but in the technical sections, they're matching the top teams.`,
  },
  {
    id: "midfield-driver-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Just had a great chat with {eighthDriver}. Despite the team's struggles, they remain positive and focused on development. Their technical feedback has been crucial in the team's recent progress.`,
  },
  {
    id: "midfield-driver-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{ninthDriver} has impressed me with their race management this season. They're consistently getting the most out of the tires and making one-stop strategies work when others can't.`,
  },
  {
    id: "midfield-driver-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{tenthDriver} is showing flashes of real talent in that midfield car. Their qualifying performances have been particularly impressive - regularly making Q3 in what's not the fastest package.`,
  },
  {
    id: "midfield-driver-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{fourthDriver} needs to capitalize more on their excellent qualifying performances. Too often they've slipped back in the races. Converting those grid positions into points will be key for the rest of the season.`,
  },
  {
    id: "midfield-driver-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{fifthDriver} has been one of the most consistent performers in the midfield. They're maximizing every opportunity and rarely making mistakes. That's why they're leading the midfield battle.`,
  },
  {
    id: "midfield-driver-10",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `Just spoke with {sixthDriver} about their season so far. They're pleased with their personal performance but pushing the team for more development. Their ambition is clear - they want to be fighting at the front.`,
  },

  // More tweets about specific midfield battles
  {
    id: "midfield-battle-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The battle between {fourthDriver} and {fifthDriver} for P4 in the drivers' championship is fascinating. They're wonderful friends off the track, though. Apparently, they took a trip to Dubai together recently.`,
  },
  {
    id: "midfield-battle-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The midfield battle at {currentRace} was absolutely thrilling! {sixthDriver}, {seventhDriver}, and {eighthDriver} were separated by less than a second for most of the race. That's what F1 is all about!`,
  },
  {
    id: "midfield-battle-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: The fight between {fourthTeam} and {fifthTeam} for P4 in the constructors' is worth approximately $10-15 million in prize money. No wonder they're throwing everything at development.`,
  },
  {
    id: "midfield-battle-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Analyzing the midfield battle, {sixthTeam} has the better car on high-downforce circuits, while {seventhTeam} excels on tracks with long straights. The remaining calendar slightly favors {sixthTeam}.`,
  },
  {
    id: "midfield-battle-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The rivalry between {fourthDriver} and {fifthDriver} is becoming one of the most entertaining on the grid. They have tremendous respect for each other off-track, but they're absolutely fierce competitors on it.`,
  },
  {
    id: "midfield-battle-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The midfield teams are separated by such fine margins this season. {fourthTeam}, {fifthTeam}, and {sixthTeam} all have different strengths and weaknesses, but they're ending up with very similar performance overall.`,
  },
  {
    id: "midfield-battle-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The battle between {seventhDriver} and {eighthDriver} reminds me of some of the great midfield rivalries of the past. Two evenly matched drivers in similar machinery, pushing each other to new heights.`,
  },
  {
    id: "midfield-battle-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{fourthDriver} vs {fifthDriver} is becoming the rivalry to watch in the midfield. They've had some fantastic wheel-to-wheel battles this season, always hard but fair. Great to see.`,
  },
  {
    id: "midfield-battle-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The fight for best of the rest between {fourthDriver}, {fifthDriver}, and {sixthDriver} is providing some of the best racing this season. They're evenly matched and taking no prisoners.`,
  },
  {
    id: "midfield-battle-10",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The atmosphere in the {fourthTeam} garage is electric right now. They've overtaken {fifthTeam} for P4 in the constructors' and are determined to hold onto it for the rest of the season.`,
  },

  // Additional tweets about specific midfield performances
  {
    id: "midfield-performance-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{fourthDriver}'s drive at {currentRace} was one of the best midfield performances I've seen this season. They extracted absolutely everything from that car and deserved their P6 finish.`,
  },
  {
    id: "midfield-performance-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `WHAT A MOVE by {fifthDriver}! Brilliant overtake around the outside of Turn 4 on {sixthDriver}. That's going straight into the season highlights reel!`,
  },
  {
    id: "midfield-performance-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {fourthTeam}'s upgrade package has delivered exactly what they promised. Their car is now much stronger in high-speed corners, which has helped them overtake {fifthTeam} in the standings.`,
  },
  {
    id: "midfield-performance-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{sixthDriver}'s qualifying lap was exceptional - P7 in a car that should realistically be fighting for P10-P12. They found over three tenths in the final sector alone. Brilliant driving.`,
  },
  {
    id: "midfield-performance-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{seventhDriver} told me they've completely changed their approach to race weekends since {currentRaceIndex - 5}. The results speak for themselves - they've scored points in {currentRaceIndex - 5} consecutive races.`,
  },
  {
    id: "midfield-performance-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{eighthDriver}'s defensive driving against {seventhDriver} in the closing laps was masterful. Firm but fair, never giving an inch but always leaving just enough space. That's how it's done.`,
  },
  {
    id: "midfield-performance-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{fourthDriver} is extracting performance from that {fourthTeam} car that reminds me of what Alonso used to do at Ferrari. They're consistently finishing higher than the car deserves to be.`,
  },
  {
    id: "midfield-performance-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{fifthDriver}'s race pace has been exceptional in recent events. They're consistently one of the fastest midfield drivers on Sundays, even if their qualifying hasn't always shown it.`,
  },
  {
    id: "midfield-performance-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{sixthDriver} has been quietly impressive this season. They've finished in the points in {currentRaceIndex - 2} of the {currentRaceIndex} races so far, which is remarkable consistency in that midfield battle.`,
  },
  {
    id: "midfield-performance-10",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `Just spoke with {fourthTeam}'s team principal about their recent form. They're delighted with {fourthDriver}'s performances and have some significant upgrades planned for the next few races.`,
  },
]
