// A large pool of tweets with placeholders for dynamic content
export const tweetPool = [
  // Martin Brundle tweets
  {
    id: "brundle-1",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Incredible performance from {topDriver} this season! The way they're driving that {topDriverTeam} car is simply masterclass. {topDriverPoints} points already and we're only at race {currentRaceIndex}.`,
  },
  {
    id: "brundle-2",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The battle between {topDriver} and {secondDriver} reminds me of the Senna-Prost era. Pure racing at its finest. This is what F1 is all about!`,
  },
  {
    id: "brundle-3",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Just walked the track at {currentRace}. Turn 4 looks particularly tricky this year with the new surface. Expect some drivers to struggle there during the race.`,
  },
  {
    id: "brundle-4",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{americarTeam} has made progress for a team in just their second season. Currently P{americarPosition} in the constructors' standings - they're working hard to move up the grid.`,
  },
  {
    id: "brundle-5",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The gap between {topTeam} and {secondTeam} is closing. We could see a real fight for the constructors' title if this trend continues.`,
  },
  {
    id: "brundle-6",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{lastRaceWinner}'s drive at the last race was exceptional. Controlled the pace perfectly and never looked troubled. Championship-caliber performance.`,
  },
  {
    id: "brundle-7",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The technical directive issued before {currentRace} could shake up the order. Several teams might need to modify their floor designs.`,
  },
  {
    id: "brundle-8",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{currentRace} has always been a circuit where driver skill can overcome car deficiencies. Expecting some surprises this weekend.`,
  },
  {
    id: "brundle-9",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Interesting to see {thirdDriver} consistently outperforming their teammate. They're extracting everything from that car.`,
  },
  {
    id: "brundle-10",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The championship battle is far from over. With {totalRaces - currentRaceIndex} races to go, there are still plenty of points on the table.`,
  },
  {
    id: "brundle-11",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Reliability could be the deciding factor in this championship. {topTeam} has had fewer DNFs than {secondTeam} so far.`,
  },
  {
    id: "brundle-12",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{americarDriver1} showing flashes of real talent. With more development on that car, they could be fighting for points more regularly.`,
  },
  {
    id: "brundle-13",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `The new regulations have certainly achieved closer racing. The field is more compressed than we've seen in years.`,
  },
  {
    id: "brundle-14",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `Tire management will be crucial at {currentRace}. The abrasive surface combined with high temperatures makes for a strategic challenge.`,
  },
  {
    id: "brundle-15",
    author: "Martin Brundle",
    handle: "MBrundleF1",
    content: `{topDriver} seems to have found another gear in recent races. Their confidence in the car is visibly growing.`,
  },

  // David Croft tweets
  {
    id: "croft-1",
    author: "David Croft",
    handle: "CroftyF1",
    content: `And it's {lastRaceWinner} who takes the win! What a drive! The championship battle is heating up as we head to {currentRace}. Can't wait for the next race weekend!`,
  },
  {
    id: "croft-2",
    author: "David Croft",
    handle: "CroftyF1",
    content: `LIGHTS OUT AND AWAY WE GO! What a start from {topDriver}! Absolutely brilliant getaway from the grid at {currentRace}!`,
  },
  {
    id: "croft-3",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The weather forecast for {currentRace} is looking unpredictable. Could we see a repeat of that crazy race in 2016? Rain always mixes things up!`,
  },
  {
    id: "croft-4",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{americarDriver1} showing impressive pace in the practice sessions. The {americarTeam} team has really found something in their setup this weekend.`,
  },
  {
    id: "croft-5",
    author: "David Croft",
    handle: "CroftyF1",
    content: `What a battle we're seeing between {topDriver} and {secondDriver} this season! Just {Math.abs(sortedDrivers[0].points - sortedDrivers[1].points)} points between them in the championship.`,
  },
  {
    id: "croft-6",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The atmosphere at {currentRace} is absolutely electric! Fans have been pouring in since early morning. Nothing quite like race day in Formula 1!`,
  },
  {
    id: "croft-7",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{topTeam} have now led the constructors' championship for {currentRaceIndex} consecutive races. Remarkable consistency from the entire team.`,
  },
  {
    id: "croft-8",
    author: "David Croft",
    handle: "CroftyF1",
    content: `Just {totalRaces - currentRaceIndex} races to go in this thrilling season! Every point will be crucial in the championship battle.`,
  },
  {
    id: "croft-9",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{lastRaceSecond} must be wondering what they need to do to beat {lastRaceWinner}. Another second place finish at the last race.`,
  },
  {
    id: "croft-10",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The start at {currentRace} is one of the most challenging on the calendar. That uphill run to Turn 1 has seen many first lap incidents over the years.`,
  },
  {
    id: "croft-11",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{americarTeam} currently P{americarPosition} in the constructors' standings. A solid foundation to build on in their second season.`,
  },
  {
    id: "croft-12",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The battle for third in the constructors' is incredibly tight! Just a handful of points separating several teams.`,
  },
  {
    id: "croft-13",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{thirdDriver} has been the surprise of the season for me. Consistently delivering strong results in that {thirdDriver.teamName} car.`,
  },
  {
    id: "croft-14",
    author: "David Croft",
    handle: "CroftyF1",
    content: `The DRS zones at {currentRace} have been adjusted this year. Should make for more overtaking opportunities into Turn 4.`,
  },
  {
    id: "croft-15",
    author: "David Croft",
    handle: "CroftyF1",
    content: `{nextRace} is just around the corner! The teams will have a quick turnaround after this weekend's race at {currentRace}.`,
  },

  // Ted Kravitz tweets
  {
    id: "kravitz-1",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Just wandering around the paddock and spotted some interesting upgrades on the {topTeam} cars. Their pace advantage is no accident - the development race is just as intense as the on-track action!`,
  },
  {
    id: "kravitz-2",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Notebook time: {secondTeam} have brought a completely redesigned floor to {currentRace}. Engineers expect to find at least 0.3 seconds per lap. Fascinating development battle!`,
  },
  {
    id: "kravitz-3",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Spotted {thirdDriver} having a long chat with their race engineer. Clearly not happy with the car balance in sector 2. They'll need to sort that before qualifying.`,
  },
  {
    id: "kravitz-4",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarTeam} garage is buzzing with activity. For a second-year team, their operation looks professional. They've brought some experienced personnel on board.`,
  },
  {
    id: "kravitz-5",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Interesting to see {topDriver}'s car up on stands in the garage. The team is making some last-minute setup changes before FP3.`,
  },
  {
    id: "kravitz-6",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{secondTeam} have brought a new front wing design to {currentRace}. It's a more aggressive concept than what we've seen from them before.`,
  },
  {
    id: "kravitz-7",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarTeam} car has a noticeably different cooling configuration for {currentRace}. The higher temperatures here require some specific adaptations.`,
  },
  {
    id: "kravitz-8",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Just spotted {lastRaceWinner} in deep discussion with their strategist. They're clearly leaving no stone unturned in their preparation.`,
  },
  {
    id: "kravitz-9",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Several teams struggling with porpoising through the high-speed sections at {currentRace}. The bumpy surface isn't helping matters.`,
  },
  {
    id: "kravitz-10",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{topTeam} have brought their largest upgrade package of the season to {currentRace}. New floor, sidepods, and rear wing. They're not resting on their laurels.`,
  },
  {
    id: "kravitz-11",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The {americarDriver1} side of the garage has opted for a different setup direction than {americarDriver2}. They're still finding their optimal window with this car.`,
  },
  {
    id: "kravitz-12",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `Tire degradation is higher than expected after the practice sessions. The teams might need to rethink their race strategies.`,
  },
  {
    id: "kravitz-13",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{thirdDriver}'s mechanics working flat out to fix an issue with the power unit cooling system. They should have it sorted before qualifying.`,
  },
  {
    id: "kravitz-14",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `The new technical directive has forced several teams to modify their floor designs. {secondTeam} seems most affected by the changes.`,
  },
  {
    id: "kravitz-15",
    author: "Ted Kravitz",
    handle: "TedKravitz",
    content: `{americarTeam} have a new technical director starting after {currentRace}. Big signing for them - previously worked at {topTeam}.`,
  },

  // Karun Chandhok tweets
  {
    id: "chandhok-1",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the telemetry data, {secondDriver} is actually faster in sector 2, but {topDriver} makes up the time in the high-speed corners. Fascinating battle between these two!`,
  },
  {
    id: "chandhok-2",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Analyzing the race pace from practice, {topTeam} still has about 0.2s advantage per lap over {secondTeam}, but tire degradation could be the deciding factor on Sunday.`,
  },
  {
    id: "chandhok-3",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The midfield battle is incredibly tight this season. Just 0.3s covers P7 to P14 in qualifying simulations. Strategy and execution will be everything.`,
  },
  {
    id: "chandhok-4",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{americarTeam}'s progress curve is impressive. Their car concept is quite unique - they've gone their own way with the sidepod design and it seems to be working for their package.`,
  },
  {
    id: "chandhok-5",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The long-run pace from {topDriver} in FP2 was consistently 0.3s faster than anyone else. They look very comfortable with their race setup.`,
  },
  {
    id: "chandhok-6",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{secondTeam} seems to be struggling with tire warm-up in the cooler conditions. Could be a factor if qualifying takes place later in the evening.`,
  },
  {
    id: "chandhok-7",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data shows {americarDriver1} is particularly strong in the technical middle sector. Their car seems well-balanced through the slower corners.`,
  },
  {
    id: "chandhok-8",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{lastRaceWinner}'s race-winning pace at the last GP was built on exceptional tire management. They were 0.2s faster than anyone else in the final stint.`,
  },
  {
    id: "chandhok-9",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The speed trap figures show {topTeam} has the straight-line advantage, while {secondTeam} is quicker through the corners. Classic F1 development trade-off.`,
  },
  {
    id: "chandhok-10",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{thirdDriver} is consistently the fastest driver through Turn 7 - a corner that requires precise weight transfer and commitment. Impressive stuff.`,
  },
  {
    id: "chandhok-11",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The {americarTeam} car is showing good straight-line speed, but they're losing time in the high-downforce sections. Clear area for development.`,
  },
  {
    id: "chandhok-12",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `Looking at the championship battle, {topDriver} has been more consistent, while {secondDriver} has had higher peaks but more off-days.`,
  },
  {
    id: "chandhok-13",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The data from practice shows the soft tire has a performance delta of around 0.8s over the medium, but degrades significantly after 15 laps.`,
  },
  {
    id: "chandhok-14",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `{topTeam} and {secondTeam} are taking different approaches to downforce levels at {currentRace}. {topTeam} has opted for more downforce, sacrificing some straight-line speed.`,
  },
  {
    id: "chandhok-15",
    author: "Karun Chandhok",
    handle: "karunchandhok",
    content: `The telemetry shows {americarDriver1} is braking later and harder than {americarDriver2} at Turn 1. Different driving styles within the same team.`,
  },

  // Will Buxton tweets
  {
    id: "buxton-1",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} showing progress in their second year. {americarDriver1} looking particularly impressive lately.`,
  },
  {
    id: "buxton-2",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `There's something special brewing at {topTeam} this season. The harmony between team and drivers, the strategic calls, the development pace. Championship material.`,
  },
  {
    id: "buxton-3",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Paddock whispers suggest {thirdDriver} might be on the move next season. Several teams showing interest. The driver market is already heating up!`,
  },
  {
    id: "buxton-4",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The atmosphere at {currentRace} is electric! Fans have been queuing since dawn. This is what makes F1 the greatest sporting spectacle on the planet.`,
  },
  {
    id: "buxton-5",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `Just had a fascinating chat with {topDriver} about their approach to {currentRace}. They're focused on the bigger picture - the championship.`,
  },
  {
    id: "buxton-6",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The relationship between {secondDriver} and their race engineer is one of the strongest on the grid. Their radio communications are always clear and precise.`,
  },
  {
    id: "buxton-7",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} has brought a significant upgrade package to {currentRace}. Their technical director seemed quietly confident when I spoke to him this morning.`,
  },
  {
    id: "buxton-8",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The paddock is buzzing with talk about {lastRaceWinner}'s performance at the last race. That level of dominance doesn't come along often.`,
  },
  {
    id: "buxton-9",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{thirdDriver} told me they've been working specifically on their qualifying performance. They know that's been their weakness this season.`,
  },
  {
    id: "buxton-10",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The team principals' press conference was spicy today! Clear tension between {topTeam} and {secondTeam} over the recent technical directive.`,
  },
  {
    id: "buxton-11",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarDriver1} has a special helmet design for {currentRace}. A tribute to their racing hero - nice touch.`,
  },
  {
    id: "buxton-12",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The drivers are all talking about the resurfaced section between Turns 5 and 7. Much smoother than last year, which should help with car balance.`,
  },
  {
    id: "buxton-13",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{topDriver} seems very relaxed despite the championship pressure. Their experience in these situations is showing.`,
  },
  {
    id: "buxton-14",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `The {secondTeam} garage has been closed to media more than usual this weekend. Something special in the works, perhaps?`,
  },
  {
    id: "buxton-15",
    author: "Will Buxton",
    handle: "wbuxtonofficial",
    content: `{americarTeam} has a new sponsor on the car this weekend. Good to see them attracting more commercial partners in their second season.`,
  },

  // Jenson Button tweets
  {
    id: "button-1",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Having raced against some of the greats, I can tell you that what {topDriver} is doing this season is special. The consistency, the race craft, the qualifying pace - complete package.`,
  },
  {
    id: "button-2",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{currentRace} was always one of my favorite circuits. The sequence through turns 5-7 is one of the most challenging in F1. Drivers who nail that section will find big time.`,
  },
  {
    id: "button-3",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Tire management will be crucial at {currentRace}. I'd expect a two-stop strategy to be fastest, but someone might try to make a one-stop work. That's where experience counts.`,
  },
  {
    id: "button-4",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Impressive to see how quickly {americarTeam} has integrated into F1. Building a team from scratch is incredibly difficult - I've seen many try and fail. They've done their homework.`,
  },
  {
    id: "button-5",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The way {topDriver} controlled the pace at the front in the last race reminded me of Lewis at his best. Making it look easy when it's anything but.`,
  },
  {
    id: "button-6",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{secondDriver} needs to focus on their qualifying performance. Starting behind {topDriver} puts them on the back foot immediately.`,
  },
  {
    id: "button-7",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarDriver1} has impressed me this season. They're extracting the maximum from that car and making very few mistakes.`,
  },
  {
    id: "button-8",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The start at {currentRace} is one of the trickiest on the calendar. The track narrows into Turn 1 and there's always the risk of contact.`,
  },
  {
    id: "button-9",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{thirdDriver} is one of the most underrated drivers on the grid. Consistently delivering results without much fanfare.`,
  },
  {
    id: "button-10",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The battle between {topTeam} and {secondTeam} reminds me of the McLaren-Ferrari days. Two great teams pushing each other to new heights.`,
  },
  {
    id: "button-11",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarTeam} has a solid foundation to build on. They've avoided the common first-year mistakes and have a clear development path.`,
  },
  {
    id: "button-12",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `Wet weather is forecast for qualifying. That could shake up the grid - some drivers excel in those conditions while others struggle.`,
  },
  {
    id: "button-13",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{lastRaceWinner}'s overtake on {lastRaceSecond} in the last race was one of the best I've seen this season. Perfectly judged.`,
  },
  {
    id: "button-14",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `The championship isn't over yet. I've seen bigger points gaps overturned in fewer races. {secondDriver} just needs a run of form.`,
  },
  {
    id: "button-15",
    author: "Jenson Button",
    handle: "JensonButton",
    content: `{americarDriver2} seems more comfortable with the car upgrades than {americarDriver1}. Different driving styles suit different car characteristics.`,
  },

  // Damon Hill tweets
  {
    id: "hill-1",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The battle between {topTeam} and {secondTeam} reminds me of some of the great team rivalries of the past. F1 at its best when the competition is this fierce!`,
  },
  {
    id: "hill-2",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{lastRaceWinner}'s drive last weekend was one of the best I've seen in years. Shades of Senna at Donington in '93. Sometimes you just have to sit back and applaud greatness.`,
  },
  {
    id: "hill-3",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The pressure in a championship fight is immense. I've been there. {topDriver} needs to stay focused on each race as it comes. One race at a time.`,
  },
  {
    id: "hill-4",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarTeam}'s approach is refreshing. They're not just here to make up the numbers. Their technical team has some innovative ideas, and they're not afraid to try something different.`,
  },
  {
    id: "hill-5",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{currentRace} has always been a circuit that rewards bravery. The high-speed sections separate the good from the great.`,
  },
  {
    id: "hill-6",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{secondDriver} needs to find consistency if they want to challenge for the title. The raw pace is there, but too many off-weekends.`,
  },
  {
    id: "hill-7",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarDriver1} is showing real potential. With more experience and a better car, they could be a future race winner.`,
  },
  {
    id: "hill-8",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The mental aspect of F1 is often overlooked. {topDriver} seems to have the psychological edge over {secondDriver} at the moment.`,
  },
  {
    id: "hill-9",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{thirdDriver} has been the surprise package this season. Consistently extracting the maximum from that car.`,
  },
  {
    id: "hill-10",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The technical regulations have produced closer racing this year. The field is more compressed than we've seen for a long time.`,
  },
  {
    id: "hill-11",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarTeam} has a solid technical foundation. Their car concept has clear potential for development.`,
  },
  {
    id: "hill-12",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{lastRaceThird}'s podium at the last race was well-deserved. They've been knocking on the door for a while.`,
  },
  {
    id: "hill-13",
    author: "Damon Hill",
    handle: "HillF1",
    content: `The championship battle will come down to who handles the pressure better. {topDriver} has the experience advantage in that regard.`,
  },
  {
    id: "hill-14",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{currentRace} is one of the most physically demanding tracks on the calendar. Driver fitness will be a factor, especially in the closing laps.`,
  },
  {
    id: "hill-15",
    author: "Damon Hill",
    handle: "HillF1",
    content: `{americarDriver2} has been overshadowed by their teammate, but there have been flashes of real speed. They just need to find consistency.`,
  },

  // Nico Rosberg tweets
  {
    id: "rosberg-1",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The mental strength of {topDriver} is impressive. Championship pressure can break you - I know that better than most! They seem completely unfazed by it all.`,
  },
  {
    id: "rosberg-2",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{secondDriver} needs to find another gear if they want to challenge for this championship. The raw pace is there, but consistency wins titles.`,
  },
  {
    id: "rosberg-3",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The start at {currentRace} is one of the most critical on the calendar. I always focused extra on my launch practice here. First corner position is everything.`,
  },
  {
    id: "rosberg-4",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `For a new team like {americarTeam}, scoring points consistently in year two is a good achievement. Their management structure is clearly working well.`,
  },
  {
    id: "rosberg-5",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{topDriver}'s qualifying performances have been exceptional this season. They've outqualified their teammate {currentRaceIndex} times already.`,
  },
  {
    id: "rosberg-6",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{secondDriver} needs to focus on their race starts. They've lost positions off the line too many times this season.`,
  },
  {
    id: "rosberg-7",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarDriver1} has impressed me with their racecraft. Clean, fair, and decisive in wheel-to-wheel situations.`,
  },
  {
    id: "rosberg-8",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The way {lastRaceWinner} managed the gap in the last race was textbook. Never pushing too hard, never allowing their rivals to get close.`,
  },
  {
    id: "rosberg-9",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{thirdDriver} needs to capitalize on their strong qualifying performances. Too often they've slipped back in the race.`,
  },
  {
    id: "rosberg-10",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The championship battle is as much psychological as it is about car performance. {topDriver} seems to have the mental edge right now.`,
  },
  {
    id: "rosberg-11",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarTeam} has a clear vision for their future in F1. Their technical structure is solid and they're making steady progress.`,
  },
  {
    id: "rosberg-12",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{currentRace} requires absolute precision. One small mistake in the high-speed sections can cost you dearly.`,
  },
  {
    id: "rosberg-13",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{lastRaceSecond} must be frustrated with another P2 finish. So close yet so far - I know that feeling well!`,
  },
  {
    id: "rosberg-14",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `The development race between {topTeam} and {secondTeam} is fascinating. Each upgrade is a direct response to the other team's innovations.`,
  },
  {
    id: "rosberg-15",
    author: "Nico Rosberg",
    handle: "NicoRosberg",
    content: `{americarDriver2} needs to find more consistency. The flashes of speed are there, but too many weekends where they're off the pace.`,
  },

  // Mark Webber tweets
  {
    id: "webber-1",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{topDriver} is in the zone right now. When a driver finds that sweet spot with their car, it's a beautiful thing to watch. Reminds me of Vettel in 2013.`,
  },
  {
    id: "webber-2",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The physicality of {currentRace} is often underestimated. Drivers will lose 3-4kg during the race. The neck and shoulder strength required is immense.`,
  },
  {
    id: "webber-3",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `Strategy calls will make or break races this season. The performance delta between teams is so small that pit timing and tire choice are more crucial than ever.`,
  },
  {
    id: "webber-4",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarTeam} has brought a fresh energy to the paddock. Their technical approach is bold - high risk, high reward. That's what we need more of in F1.`,
  },
  {
    id: "webber-5",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{topDriver}'s ability to extract the maximum from the car in qualifying is remarkable. They're consistently finding those extra few tenths.`,
  },
  {
    id: "webber-6",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{secondDriver} needs to focus on their race pace. They're often quick over one lap but struggle to maintain that pace over a full stint.`,
  },
  {
    id: "webber-7",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarDriver1} has shown good racecraft this season. Clean but assertive in wheel-to-wheel battles.`,
  },
  {
    id: "webber-8",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The way {lastRaceWinner} controlled the race from the front last weekend was impressive. Never looked under pressure.`,
  },
  {
    id: "webber-9",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{thirdDriver} is extracting everything from that car. They're consistently outperforming what the package should be capable of.`,
  },
  {
    id: "webber-10",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The championship battle will come down to who makes fewer mistakes. The pressure is building with each race.`,
  },
  {
    id: "webber-11",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarTeam} has a solid foundation to build on. Their car concept has clear potential for development.`,
  },
  {
    id: "webber-12",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{currentRace} is one of the most physically demanding tracks on the calendar. The g-forces through the high-speed corners are brutal.`,
  },
  {
    id: "webber-13",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{lastRaceThird}'s podium at the last race was well-deserved. They've been knocking on the door for a while.`,
  },
  {
    id: "webber-14",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `The development race between {topTeam} and {secondTeam} is fascinating. Each upgrade is a direct response to the other team's innovations.`,
  },
  {
    id: "webber-15",
    author: "Mark Webber",
    handle: "AussieGrit",
    content: `{americarDriver2} has shown flashes of real speed. With more experience, they could be a regular points scorer.`,
  },

  // Natalie Pinkham tweets
  {
    id: "pinkham-1",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `Just interviewed {topDriver} - they're quietly confident about their chances at {currentRace}. The team has found something in the setup that's working really well.`,
  },
  {
    id: "pinkham-2",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The atmosphere in the {topTeam} garage is so positive right now. Everyone pulling in the same direction. That harmony translates to performance on track.`,
  },
  {
    id: "pinkham-3",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `Fascinating chat with {americarTeam}'s Team Principal about their five-year plan. They're working hard on development and have clear goals.`,
  },
  {
    id: "pinkham-4",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The fan turnout at {currentRace} is incredible! F1's popularity continues to soar. Sold-out grandstands and an electric atmosphere around the circuit.`,
  },
  {
    id: "pinkham-5",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{secondDriver} seemed frustrated after qualifying. They feel there's more performance in the car that they haven't been able to extract.`,
  },
  {
    id: "pinkham-6",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The {secondTeam} engineers were working late into the night. They've been making significant setup changes to find more pace.`,
  },
  {
    id: "pinkham-7",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{americarDriver1} was in good spirits when I spoke to them this morning. They're happy with the progress the team is making.`,
  },
  {
    id: "pinkham-8",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{lastRaceWinner} is still buzzing from their win at the last race. That victory has given them and the team a huge confidence boost.`,
  },
  {
    id: "pinkham-9",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{thirdDriver} told me they've been working specifically on their qualifying performance. They know that's been their weakness this season.`,
  },
  {
    id: "pinkham-10",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The paddock is buzzing with talk about the championship battle. Everyone expects {currentRace} to be a crucial turning point.`,
  },
  {
    id: "pinkham-11",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{americarTeam}'s hospitality unit has been busy with potential sponsors this weekend. Their P{americarPosition} in the constructors' is attracting commercial interest.`,
  },
  {
    id: "pinkham-12",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The drivers are all talking about the resurfaced section between Turns 5 and 7. Much smoother than last year, which should help with car balance.`,
  },
  {
    id: "pinkham-13",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{topDriver} seems very relaxed despite the championship pressure. Their experience in these situations is showing.`,
  },
  {
    id: "pinkham-14",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `The {secondTeam} garage has been closed to media more than usual this weekend. Something special in the works, perhaps?`,
  },
  {
    id: "pinkham-15",
    author: "Natalie Pinkham",
    handle: "NataliePinkham",
    content: `{americarDriver2} has a special helmet design for {currentRace}. A tribute to their racing hero - nice touch.`,
  },

  // Lawrence Barretto tweets
  {
    id: "barretto-1",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Sources tell me {secondTeam} is planning a major upgrade package for {nextRace}. They're throwing everything at this championship battle.`,
  },
  {
    id: "barretto-2",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Hearing that {thirdDriver} has been putting in the hours on the simulator. They've identified the issues from last race and are confident they've found solutions.`,
  },
  {
    id: "barretto-3",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Paddock talk suggests {americarTeam} is already working on next year's car concept. Their technical director has big ambitions.`,
  },
  {
    id: "barretto-4",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Team bosses meeting ran long today. Discussions about cost cap regulations and the 2026 rule changes getting heated. Politics is never far from the surface in F1.`,
  },
  {
    id: "barretto-5",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `My sources at {topTeam} say they're confident they've solved the reliability issues that have plagued them in recent races.`,
  },
  {
    id: "barretto-6",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Interesting whispers about {secondDriver}'s future. Their contract is up at the end of the season and several teams are showing interest.`,
  },
  {
    id: "barretto-7",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `{americarTeam} is set to announce a new technical partnership next week. Part of their long-term plan to move up the grid.`,
  },
  {
    id: "barretto-8",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `The word in the paddock is that {lastRaceWinner} has found a new setup direction that's unlocked significant performance.`,
  },
  {
    id: "barretto-9",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Hearing that {thirdDriver}'s team is bringing their largest upgrade package of the season to {nextRace}. They're targeting a significant step forward.`,
  },
  {
    id: "barretto-10",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Sources close to {topTeam} say they're already shifting some resources to next year's car. They're confident in their current package.`,
  },
  {
    id: "barretto-11",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `{americarTeam} is in talks with several experienced engineers from top teams. They're looking to strengthen their technical department.`,
  },
  {
    id: "barretto-12",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `The FIA is keeping a close eye on flexible wings this weekend. Several teams have been asked to make modifications.`,
  },
  {
    id: "barretto-13",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Interesting to hear that {topDriver} has been working specifically on their race starts. That's been a relative weakness this season.`,
  },
  {
    id: "barretto-14",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `My sources at {secondTeam} say they've found a significant performance gain in the wind tunnel. The challenge now is translating that to the track.`,
  },
  {
    id: "barretto-15",
    author: "Lawrence Barretto",
    handle: "LawroBarretto",
    content: `Hearing that {americarDriver1} is very happy with the latest upgrades. They feel the car is now more suited to their driving style.`,
  },
]
